apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.21.45"],"port":9200,"protocol":"TCP","serviceName":"default:elasticsearch-oss-7-nodeport","allNodes":true},{"addresses":["192.168.21.45"],"port":9300,"protocol":"TCP","serviceName":"default:elasticsearch-oss-7-nodeport","allNodes":true}]'
    field.cattle.io/targetWorkloadIds: '["deployment:default:elasticsearch-oss-7"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: "2020-06-03T11:48:55Z"
  labels:
    cattle.io/creator: norman
  name: elasticsearch-oss-7-nodeport
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: elasticsearch-oss-7
    uid: 42228278-bd9b-40d6-973c-23fa16f9eabc
  resourceVersion: "187970"
  selfLink: /api/v1/namespaces/default/services/elasticsearch-oss-7-nodeport
  uid: d59d33d5-899e-4b68-aa0e-4529ae1ea832
spec:
  clusterIP: 10.43.169.237
  externalTrafficPolicy: Cluster
  ports:
  - name: 9200tcp92001
    nodePort: 9200
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: 9300tcp93001
    nodePort: 9300
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-elasticsearch-oss-7
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

