apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.21.45"],"port":31358,"protocol":"TCP","serviceName":"default:dejavu-nodeport","allNodes":true}]'
    field.cattle.io/targetWorkloadIds: '["deployment:default:dejavu"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: "2020-06-03T05:21:03Z"
  labels:
    cattle.io/creator: norman
  name: dejavu-nodeport
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: dejavu
    uid: b1000ad9-b784-4c70-ab8b-55edfdb72426
  resourceVersion: "204754"
  selfLink: /api/v1/namespaces/default/services/dejavu-nodeport
  uid: 06004678-8804-40b2-b8bb-c1f66a3e787e
spec:
  clusterIP: 10.43.126.47
  externalTrafficPolicy: Cluster
  ports:
  - name: 1358tcp313581
    nodePort: 31358
    port: 1358
    protocol: TCP
    targetPort: 1358
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-dejavu
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

